#!/bin/sh

case "$1" in
	start)
		echo "Loading scull module" >> /var/log/scullmodule.log
		./usr/bin/scull_module_load scull >> /var/log/scullmodule.log 2>&1
		;;
	stop)
		echo "Unloading scull module"
		./usr/bin/scull_module_unload scull >> /var/log/scullmodule.log 2>&1
		;;
	*)
		echo "Usage: $0 {load|unload}"
		exit 1
esac
exit 0
