#!/bin/sh

case "$1" in
	start)
		echo "Loading faulty and hello modules" >> /var/log/miscmodules.log
		./usr/bin/misc_module_load faulty >> /var/log/miscmodules.log 2>&1
		./usr/bin/misc_module_load hello  >> /var/log/miscmodules.log 2>&1
		;;
	stop)
		echo "Unloading faulty and hello modules"
		./usr/bin/misc_module_unload faulty
		./usr/bin/misc_module_unload hello
		;;
	*)
		echo "Usage: $0 {load|unload}"
		exit 1
esac
exit 0
